[package]
name = "nadi-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "nadi_py"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.89"
nadi_core = { version="0.6.0", features=["functions"]}
pyo3 = { version = "0.22.0", features = ["anyhow"] }
