[package]
name = "mdbook-nadi"
version = "0.8.1"
edition = "2021"
description = "mdbook plugin for nadi DSL"
repository = "https://github.com/Nadi-System/nadi-system"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.*"
clap = "4.*.*"
serde = "1.0.*"
serde_json = "1.0.*"
pulldown-cmark = "0.13.0"
pulldown-cmark-to-cmark = "21.1.0"
nadi_core = {version="0.8.1", path = "../nadi_core/", features=["parser", "functions"]}
strip-ansi-escapes = "0.2.1"
gag = "1.0.0"
mdbook-preprocessor = "0.5.2"
mdbook-markdown = "0.5.2"
