[package]
name = "nadi-ide"
version = "0.8.0"
edition = "2024"
description = "Integrated Development Environment (IDE) for running nadi task system"
repository = "https://github.com/Nadi-System/nadi-system"
license = "GPL-3.0-only"
readme = "README.md"
default-run = "nadi-ide"

[dependencies]
iced = { git = "https://github.com/atreyagaurav/iced.git", branch="cargo-stable", features = ["highlighter", "markdown", "lazy", "tokio", "svg", "canvas"] }
nadi_core = { version = "0.8.0", path="../nadi_core", features = ["functions"] }

tokio = {version = "1.44.1", features = ["fs"]}
rfd = "0.13"
gag = "1.0.0"
iced_core = {git = "https://github.com/atreyagaurav/iced.git", branch="cargo-stable"}
iced_graphics = { git = "https://github.com/atreyagaurav/iced.git", branch="cargo-stable", features = ["geometry"] }
webbrowser = "1.0.4"

[dev-dependencies]
rstest = "0.25.0"
